### ISSUE TITLE
Code accuracy

### ISSUE THREAD

**Issue by Suntrie** [HaveAHeart/--uniq#2]
1. В текущей версии проекта довольно большое количество code replication - особенно в тестах. В таких случаях стоит подумать о выделении вспомогательных функций;

2. Выбранная библиотека поддерживает декларирование зависимостей флагов [на уровне аннотаций](http://args4j.kohsuke.org/apidocs/org/kohsuke/args4j/Option.html#forbids());

3. Обработка catch-ей в тестах довольно неинформативна, возможно, стоит просто выкидывать исключения наверх (throws).

**Comment by HaveAHeart** [comment]
1 - fixed - большая часть кода вынесена в вспомогательную функцию.
2 - fixed
3 - fixed
