### ISSUE TITLE
Implementation issues

### ISSUE THREAD

**Issue by Suntrie** [HaveAHeart/--uniq#3]
1. Что произойдёт, если входной файл будет содержать единственную строку?

2. При каких входных данных `compare(tempLine, lines.get(lines.size() - 1))` в iterating(..) может вернуть что-то, кроме true?

3. Разные операционные системы используют разные символы для представления [конца строки](https://docs.oracle.com/javase/7/docs/api/java/io/BufferedWriter.html#newLine()), поэтому разработанные тесты пройдут не везде.

**Comment by HaveAHeart** [comment]
1 - fixed, обсуждали с вами
2 и 3 - аналогично
