### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Suntrie** [HaveAHeart/--uniq#4]
1. Дефолтный layout Maven предполагает наличие папки test/resources, в которую должны попадать все файлы проекта с расширением, отличным от java. Существуют специальные методы для работы с ресурсами - см. [обсуждение](https://stackoverflow.com/questions/28673651/how-to-get-the-path-of-src-test-resources-directory-in-junit);

2. Пожалуйста, добавьте 1-2 теста, иллюстрирующих работу с консольным вводом.

**Comment by HaveAHeart** [comment]
1 - fixed, обсудили - не использую getClass().getResource("filler").getFile() потому что мне необходим путь к файлу -> легче и более читаемо прописать один раз относительный путь src\test\resources и использовать его как переменную testDir, нежели для каждого файла прописывать данную цепочку методов. 
2 - жду ответа, при подмене системного потока ввода кастомным сканер отказывается читать более сем одну строку.

**Comment by Suntrie** [comment]
1. main и resources - обычно, всё-таки, не пакеты. 
`Path resourceDirectory = Paths.get("src","test","resources");` (см. ссылку выше) - всё же выглядит несколько более наглядно, чем ручное конструирование с помощью File.PathSeparator;

2. У Вас создаётся каждый раз новый сканер, с одним всё будет ок (кроме того, что ожидаемый вывод так же стоит поправить). Также обращаю Ваше внимание, что сканер - это ресурс и его надо закрывать:)

**Comment by HaveAHeart** [comment]
1 - fixed, однако, приходится создавать новый объект класса path для каждого файла, к которому я хочу получить доступ - иначе приходится использовать File.pathSeparator()
2 - fixed, для адекватной работы со сканером, в том числе для его закрытия, избавился от вспомогательного метода для получения одной строки, чтобы не создавать/закрывать сканер для каждой отдельной строки
