### ISSUE TITLE
Remaining

### ISSUE THREAD

**Issue by Suntrie** [HaveAHeart/--uniq#5]
1. Не вполне понятна текущая логика задания областей видимости - package-private class + public методы?

2. В методах getLines(..)/ returnLines(..) остаётся дублирование кода;

3. Проблема с разделителями строк пока остаётся - см. println и внутренний "\n";

4. Некритично, но обычно имя класса и файла делают совпадающими (см. Main).

**Comment by HaveAHeart** [comment]
1 - fixed, изначально хотел сделать Unique public - классом, но, видимо, просто забыл дописать
2 - в getLines - fixed, действительно, вынесение дублирующегося кода в отдельный вспомогательный метод стоит того. Однако, в returnLines это делать не очень резонно - системное сообщение в вспомогательный метод запихнуть не получится(при ошибке доступа к файлу, в который происходит запись, я указываю это дополнительно), а без подобного сообщения из дублирующегося кода там один for - цикл, спокойно вмещающийся в одну строку.
3 - fixed, каюсь, не всё просмотрел в первый раз :c
